apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 783764611818.dkr.ecr.us-east-1.amazonaws.com/sql      ####REPLACE WITH YOUR IMAGE URL
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "sre_hub"
          ports:
            - containerPort: 3306
